import logging
import hashlib
from datetime import datetime, timezone
from sqlalchemy.orm import Session

from app.models.qr_token import QRToken
from app.models.scan_event import ScanEvent

from app.enum.qr_action import QRAction
from app.enum.attendance_status import AttendanceStatus
from app.enum.scan_result import ScanResult

def consume_entry_qr(raw_token: str, current_user_id: int, station_id: int, db_session: Session):
    """
    Step 2 (ENTRY): Consumes the ENTRY QR after manual volunteer verification.
    MUST re-verify rules to prevent Time-of-Check to Time-of-Use race conditions.
    """
    now = datetime.now(timezone.utc)
    token_hash = hashlib.sha256(raw_token.encode('utf-8')).hexdigest()

    # 1. Cryptographic and Token State Re-Check
    qr_token = db_session.query(QRToken).filter_by(token_hash=token_hash).first()
    
    if not qr_token:
        return {"error": "Invalid QR code."}, 403
    if qr_token.action != QRAction.ENTRY:
        return {"error": "Invalid token action. Expected ENTRY."}, 403
    if qr_token.consumed_at is not None:
        return {"error": "QR code has already been used."}, 403
    if now >= qr_token.expires_at:
        return {"error": "QR code has expired."}, 403

    # 2. Relationship Re-Guards
    registration = qr_token.registration
    if not registration:
        return {"error": "Associated registration not found."}, 404
        
    event = registration.event
    if not event:
        return {"error": "Associated event not found."}, 404
        
    attendance = registration.attendance
    if not attendance:
        return {"error": "Attendance record not found."}, 404

    # 3. Time Window & Sequence Re-Rules
    if not (event.entry_open_at <= now <= event.entry_close_at):
        return {"error": "Outside of event entry window."}, 403
    if attendance.entry_status != AttendanceStatus.PENDING:
        return {"error": "User has already entered."}, 403

    # 4. Atomic Consumption and Updates
    try:
        # Mark token as consumed
        qr_token.consumed_at = now
        
        # Create ScanEvent record (receipt_at is auto-generated by DB)
        new_scan = ScanEvent(
            registration_id=registration.id,
            token_id=qr_token.id,
            actor_id=current_user_id,
            station_id=station_id,
            action=QRAction.ENTRY,
            result=ScanResult.VALID,
            reason=None
        )
        db_session.add(new_scan)

        # Update Attendance State using shared verification fields
        attendance.entry_status = AttendanceStatus.SCANNED
        attendance.entry_at = now
        attendance.verified_by = current_user_id
        attendance.station_id = station_id
        attendance.verified_at = now

        db_session.commit()
        
        return {
            "message": "Entry successfully verified and recorded.",
            "registration_id": registration.id
        }, 200

    except Exception as e:
        db_session.rollback()
        logging.error(f"Error consuming ENTRY QR (Token ID: {qr_token.id}): {str(e)}")
        return {"error": "Internal server error during entry consumption."}, 500