import enum

class AuditEventType(str, enum.Enum):
    REGISTRATION_CREATED = "REGISTRATION_CREATED"
    QR_ISSUED = "QR_ISSUED"
    ATTENDANCE_CHANGED = "ATTENDANCE_CHANGED"
    EXIT_OPENED = "EXIT_OPENED"
    BULK_EXIT_SENT = "BULK_EXIT_SENT"
    OD_GENERATED = "OD_GENERATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    EVENT_CONFIG_CHANGED = "EVENT_CONFIG_CHANGED"