[project]
name = "server"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
  "aiocache>=0.12.3",
  "gotrue>=2.12.4",
  "fastapi[standard]",
  "jose>=1.0.0",
  "passlib>=1.7.4",
  "pillow>=12.1.0",
  "pydantic>=2.0",
  "pydantic-settings>=2.0",
  "python-dotenv>=1.0",
  "python-jose>=3.5.0",
  "python-multipart>=0.0.9",
  "uvicorn>=0.27",
  "sqlalchemy>=2.0.52",
  "alembic>=1.19.1",
  "psycopg[binary]>=3.3.4",
  "psycopg2>=2.9.12",
]
