"""update event timing and scan event fields

Revision ID: a1c9683243f5
Revises: b5a817f5e8de
Create Date: 2026-08-20 14:14:23.598541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1c9683243f5'
down_revision: Union[str, Sequence[str], None] = 'b5a817f5e8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('entry_open_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('entry_close_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('exit_close_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('check_exit_open_within_event'), 'events', type_='check')
    op.drop_constraint(op.f('check_start_before_end'), 'events', type_='check')
    op.create_check_constraint('check_entry_before_exit', 'events', 'entry_close_at <= exit_open_at')
    op.create_check_constraint('check_entry_open_before_close', 'events', 'entry_open_at < entry_close_at')
    op.create_check_constraint('check_exit_open_before_close', 'events', 'exit_open_at < exit_close_at')
    op.drop_column('events', 'start_at')
    op.drop_column('events', 'end_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('check_exit_open_before_close', 'events', type_='check')
    op.drop_constraint('check_entry_open_before_close', 'events', type_='check')
    op.drop_constraint('check_entry_before_exit', 'events', type_='check')
    op.create_check_constraint(op.f('check_start_before_end'), 'events', 'start_at < end_at')
    op.create_check_constraint(op.f('check_exit_open_within_event'), 'events', 'start_at <= exit_open_at AND exit_open_at <= end_at')
    op.drop_column('events', 'exit_close_at')
    op.drop_column('events', 'entry_close_at')
    op.drop_column('events', 'entry_open_at')
    # ### end Alembic commands ###
