"""update database structure

Revision ID: b5a817f5e8de
Revises: acc54b03b92b
Create Date: 2026-08-18 22:41:57.666628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5a817f5e8de'
down_revision: Union[str, Sequence[str], None] = 'acc54b03b92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_target_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_target_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.alter_column('scan_events', 'actor_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('scan_events', 'station_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_events', 'station_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('scan_events', 'actor_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('event_type', postgresql.ENUM('REGISTRATION_CREATED', 'QR_ISSUED', 'ATTENDANCE_CHANGED', 'EXIT_OPENED', 'BULK_EXIT_SENT', 'OD_GENERATED', 'ROLE_CHANGED', 'EVENT_CONFIG_CHANGED', name='auditeventtype'), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_events_actor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_target_type'), 'audit_events', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_events_target_id'), 'audit_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    # ### end Alembic commands ###
